---
- name: Ensure tmp directory is present
  file:
    path: "{{ temp_dir }}"
    state: directory

- name: Check if dotfiles directory is present
  stat:
    path: "{{ dotfiles_path }}"
  register: stat_result

- name: Clone dotfiles from repo
  git:
    repo: "{{ dotfiles_repo_url }}"
    dest: "{{ dotfiles_path }}"
  when: not stat_result.stat.exists

- name: Pull dotfiles from repo
  shell: git pull
  args:
    chdir: "{{ dotfiles_path }}"
  when: stat_result.stat.exists

- name: Link dotfiles and exclude meta files
  command: rcup -d "{{ dotfiles_path }}" -f '{% for arg1 in excluded_files %}-x {{arg1 }}{% if not loop.last %}{% endif %} {% endfor %}' #-x README -x LICENSE -x screenshot.png
  args:
    chdir: "{{ ansible_env.HOME }}/workspace/github.com/allaman/public-dotfiles"

- name: Create global gitconfig
  template:
    src: templates/gitconfig.j2
    dest: "{{ ansible_env.HOME }}/.gitconfig"
    force: true
