---
# tasks file for ansible-role-shell
- name: Ensure ~/.shell exists
  file:
    path: ~/.shell
    state: directory

- name: Clone Tmux TPM
  git:
    clone: true
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm

- name: Download kubectl aliases
  get_url:
    url: https://raw.githubusercontent.com/ahmetb/kubectl-alias/master/.kubectl_aliases
    dest: ~/.shell/kubectl_aliases

- name: Install forgit
  git:
    clone: true
    repo: https://github.com/wfxr/forgit.git
    dest: ~/.shell/forgit

- name: Install zsh-autosuggestions
  git:
    clone: true
    repo: https://github.com/zsh-users/zsh-autosuggestions
    dest: ~/.shell/zsh-autosuggestions

- name: Install Fast Syntax Highlighting
  git:
    clone: true
    repo: https://github.com/zdharma-continuum/fast-syntax-highlighting
    dest: ~/.shell/fast-syntax-Highlighting

- name: Install zsh-completions
  git:
    clone: true
    repo: https://github.com/zsh-users/zsh-completions
    dest: ~/.shell/zsh-completions

- name: Install powerlevel10k
  git:
    clone: true
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: ~/.shell/powerlevel10k

- name: Clone NeoVim config
  git:
    clone: true
    repo: https://github.com/allaman/nvim.git
    dest: ~/.config/nvim
